### ISSUE TITLE
error when registering for polymny sudio

### ISSUE THREAD

**Issue by gwmatthews** [polymny/polymny#20]
In the English site when I try to create a new account, the second password field where you should reenter the password,  multiplies off the screen and cannot be filled. Here is a screenshot running the latest Chrome browser in 64 bit current Linux Mint.

![polymny](https://user-images.githubusercontent.com/57901986/99879670-4b3cb000-2bdc-11eb-8411-7d39732e0594.png)

Reproducible by me at least. I tried twice with the same results.

**Comment by tforgione** [comment]
Hum... this is weird.

> In the English site

What do you mean by the english site ? If I'm not mistaken, there should be no english site yet, so accessing this page in the first place might be the bug. When I go to [polymny.studio](https://polymny.studio), I land on the french home page, and the login and sign up forms seems to work fine from there. How do you go to the english site ?

**Comment by gwmatthews** [comment]
Thanks for the response. Oh I see, I must have clicked on the Google Translate button for English then. NOT, doing that has enabled me to register.

**Comment by gwmatthews** [comment]
CLOSED. Problem solved.
