### ISSUE TITLE
Ajout d'un compteur lors de l'enregistrement

### ISSUE THREAD

**Issue by jubonhomme** [polymny/polymny#39]
Bonjour,
Je trouverais utile d'avoir un compteur à côté du bouton "REC" lors de l'enregistrement vidéo / audio

Une proposition en image : 
![image](https://user-images.githubusercontent.com/29262866/211427389-3be76ac9-acb9-4b6d-a5e6-12e80b3dc277.png)

Merci pour ce super outil !

**Comment by tforgione** [comment]
Merci pour vos retours.

Fonctionnalité implémentée dans https://github.com/polymny/polymny/commit/3fd13c0bf940c920cf8d178ed80020e8e6362eaf

Sortira en même temps que la v2.0.0.

**Comment by jubonhomme** [comment]
Merci à vous !
